"""empty message

Revision ID: 63b9da387c9b
Revises: 4a76d17fe0ff
Create Date: 2020-03-30 19:03:47.134581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b9da387c9b'
down_revision = '4a76d17fe0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_artist_id_fkey', 'show', type_='foreignkey')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('show_artist_id_fkey', 'show', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
