"""empty message

Revision ID: 98d6633c0955
Revises: 3f645204475d
Create Date: 2020-03-30 16:32:10.484537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d6633c0955'
down_revision = '3f645204475d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('show_venue_id_fkey', 'show', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###
